a) Démontrez, par induction ou autrement, que les vecteurs $q_i$ sont orthonormaux.

Ces vecteurs sont construits comme:
$$u_0 = a_0 
\\ u_1 = a_1 - (q_0\cdot a_1)q_0  
\\ u_2 = a_2  - (q_0\cdot a_2)q_0  - (q_1\cdot a_2)q_1  
 \\q_0 = \frac{u_0}{|u_0|}
 \\q_1=\frac{u_1}{|u_1|}
 \\q_2=\frac{u_2}{|u_2|}$$
 
 on remarque rapidement que les vecteurs $u_i$ sont orthogonaux par contruction. En effet, $u_1$ est simplement la soustraction entre $a_1$ et sa projection sur la direction de $a_0$. La résultante est alors nécessairement orthogonale à $a_0$ et donc $u_0$. Il est est de même pour $u_2$ qu'on force à être orthogonal à $u_1$ et $u_0$ de la même façon.
 
 Nous savons donc que les vecteurs $u_i$ sont nécessairement orthogonaux. Comme les $q_i$ sont simplement les vecteurs $u_i$ avec une norme de 1, les vecteurs $q_i$ sont alors nécessairement orthonormés par construction.

b) En suivant les instructions de l'énoncé du devoir, il est possible de reconstruire les matrices Q et R pour toute matrice d'entrée. En effet, comme Q et R sont simplement composés de $a_i$, $u_i$ et $q_i$, nous utilisons simplement les relations du numéro précédent pour les calculer. Le code suivant commence calculer tous ces vecteurs, puis les insère dans les matrices Q et R de façon appropriée. 

In [1]:
import numpy as np

In [2]:
def mat_a_QR(A):

    A = A.T
    Q_trans = np.copy(A) *0
    R_trans = np.copy(A) *0
    
    u_liste = []
    q_liste = []
    a_liste = []
    
    for i in range(len(A)):
        ai = np.array(A[i][:])
        ui = ai
        for j in range(i):
            ui = np.subtract(ui, np.dot(q_liste[j], ai)*q_liste[j])
        q_liste.append(ui/np.linalg.norm(ui))
        u_liste.append(ui)
        a_liste.append(ai)
    
    for i in range(len(A)):
        R_trans[i][i] = np.linalg.norm(u_liste[i])
        for j in range(i+1,len(A)):
            R_trans[i][j] = np.dot(q_liste[i],a_liste[j])

    return np.array(q_liste).T, R_trans

               
A = np.array([[1.0,4.0,8.0,4.0], [4.0,2.0,3.0,7.0],[8.0,3.0,6.0,9.0],[4.0,7.0,9.0,2.0]])
Q,R = mat_a_QR(A)
print("A = \n{},\n Q = \n{},\n R = \n{},\n QR = \n{}".format(A,Q,R,np.dot(Q,R)))


A = 
[[ 1.  4.  8.  4.]
 [ 4.  2.  3.  7.]
 [ 8.  3.  6.  9.]
 [ 4.  7.  9.  2.]],
 Q = 
[[ 0.10153462  0.558463    0.80981107  0.1483773 ]
 [ 0.40613847 -0.10686638 -0.14147555  0.8964462 ]
 [ 0.81227693 -0.38092692  0.22995024 -0.37712564]
 [ 0.40613847  0.72910447 -0.5208777  -0.17928924]],
 R = 
[[  9.8488578    6.49821546  10.55960012  11.37187705]
 [  0.           5.98106979   8.4234836   -0.484346  ]
 [  0.           0.           2.74586406   3.27671222]
 [  0.           0.           0.           3.11592335]],
 QR = 
[[ 1.  4.  8.  4.]
 [ 4.  2.  3.  7.]
 [ 8.  3.  6.  9.]
 [ 4.  7.  9.  2.]]


c) Écrire un programme permattant de calculer les vecteurs propres et valeurs propres d'une matrice carrée réelle.

Les étapes à suivre pour obtenir les valeurs et vecteurs propres à partir des matrices Q et R sont, selon la page 244 du Newmann,:
\begin{enumerate}
\item Créer V, une matrice NxN, qui contiendra les vecteurs propres et l'initialiser comme étant la matrice identité. On sélectionne aussi un seuil $\epsilon$ pour plus tard.
\item On calcule la décomposition QR de la matrice A
\item On actualise A à $A = RQ$
\item On multiplie Q à V par la droite
\item On vérifie si les valeurs hors diagonales sont inférieurs à la valeur seuil
\end{enumerate}
À la fin de l'algorithme, nous avons effectivement diagonalisé A. Ses valeurs propres sont ainsi les valeurs sur la diagonale. Le ma matrice V contient aussi les vecteurs propres dans ses colonnes. Nous avons donc effectivement extrait les valeurs et vecteurs propres de la matrice A.

In [13]:
A = np.array([[1.0,4.0,8.0,4.0], [4.0,2.0,3.0,7.0],[8.0,3.0,6.0,9.0],[4.0,7.0,9.0,2.0]])

def extract_eigenvalues(A, epsilon = 1e-9):
    V = np.identity(len(A))
    condition = True
    while condition:
        condition = False
        Q,R = mat_a_QR(A)
        A = np.dot(R,Q)
        for x in range(len(A)):
            for y in range(len(A)):
                if x!=y:
                    if A[x,y] > epsilon:
                        condition = True
        V = np.dot(V,Q)
    eigenvalues = []
    for x in range(len(A)):
        eigenvalues.append(A[x,x])
    return eigenvalues, V

values, vectors = extract_eigenvalues(A)
print(values,"\n",  vectors)

[21.0, -8.0000000000000018, -2.9999999999999991, 1.0] 
 [[ 0.43151697  0.38357064  0.77459667 -0.25819889]
 [ 0.38357064 -0.43151697  0.25819889  0.77459667]
 [ 0.62330229 -0.52740963 -0.25819889 -0.51639778]
 [ 0.52740963  0.62330229 -0.51639778  0.25819889]]
